### ISSUE TITLE
Podspec for CocoaPods?

### ISSUE THREAD

**Issue by winkelsdorf** [s-faychatelard/JSQSystemSoundPlayer-Swift#1]
Would you mind adding a PodSpec for CocoaPods? See the source Repo for an example:
https://github.com/jessesquires/JSQSystemSoundPlayer/blob/develop/JSQSystemSoundPlayer.podspec

Cheers,
Frederik

**Comment by s-faychatelard** [comment]
Pushed a podspec, is that what you needed?

Cheers

**Comment by winkelsdorf** [comment]
Yes :) See the merge comment, just needed a minor adjustment. Thank you!
